language: ruby
rvm:
  - 2.6
  - ruby-head
script: bundle exec rspec
gemfile:
  - gemfiles/rails5.gemfile
  - gemfiles/rails6.gemfile
notifications:
  email:
    - support@travellink.com.au
sudo: false
cache: bundler
